# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "光阴的故事 | Valar Morghulis"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vvl.me" # the base hostname & protocol for your site
background_image: "/images/background.png"
owner:
  index: "忽而今夏<br>
          夏至未至<br>
          今日的那个它~"
  avatar: "/images/avatar.png"
  talk: "Everything that<br>
        has a beginning has an end.<br>
        I created it<br>
        just hope to write<br>
        some footprints."
  email: "feather12315@live.com"
  github_username: "time-river"

commit:
  bool: true
  disqus_shortname: "footsetp"

analytics:
  bool: true
  google_analytics: 'UA-70087486-1'
  
navigation:
  home: "の"
  style: "脚印"
  local_movies: "足迹"
  timeline: "时间轴"
  near_me: "关于"
  header_image: "/images/psb.jpg"
  background_image: "/images/nav.jpg"
# Build settings
markdown: kramdown
kramdown:
  input: GFM #Github Flavored Markdown