# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
background_image: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vvl.me" # the base hostname & protocol for your site

owner:
  avatar: "/images/avatar.png"
  talk: "Everything that<br>
        has a beginning has an end.<br>
        I created it<br>
        just hope to write<br>
        some footprints."
  email: "feather12315@live.com"
  github_username: "time-river"

navigation:
  home: "终点即原点"
  style: "光阴的故事"
  local_movies: "尘封的记忆"
  timeline: "时间之河流"
  near_me: "关于"
  header_image: "/images/psb.jpg"
  background_image: "images/background.png"
# Build settings
markdown: kramdown
kramdown:
  input: GFM #Github Flavored Markdown
